workflow:
  rules:
    - if:$CI_COMMIT_BRANCH != "main"
      when: never
      when: always

stages:
  - teste
  - build
  - deploy

executar_teste: 
  stage: teste
  before_script:  
    - echo "Preparando testes"
    - chmod +x ./script.sh
  script:
    - ./sript.sh
  after_script: 
    - echo "Apagando arquivos temporários.."

executar_teste2:
  stage: teste
  script:
    - echo "executando teste 2..."

criar_imagens: 
  stage: build
  script:
    -echo "Criando as imagens.."

push_imagens:  
  needs: 
    - criar_imagens
  stage: build
  script:
    - echo "Realizando upload das imagens.."

kubernetes:
  stage: deploy
  script:
    - echo "executando deploy"